export const USER_ROLES = {
    STUDENT: 'STUDENT',
    ADMINISTRATOR: 'ADMINISTRATOR',
    ADMISSIONS_OFFICER: 'ADMISSIONS_OFFICER',
    PROGRAM_COORDINATOR: 'PROGRAM_COORDINATOR',
    SUPER_ADMIN: 'SUPER_ADMIN',
}